src/Entity/BlogPost.php
<?php

namespace App\Entity;

use App\Repository\BlogPostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: BlogPostRepository::class)]
class BlogPost
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\ManyToOne(inversedBy: 'blogPosts')]
    private ?BlogPostTemplate $template = null;

    #[ORM\Column]
    private ?bool $active = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $featuredImage = null;

    #[ORM\Column]
    private ?bool $titleVisible = null;

    #[ORM\Column]
    private ?bool $contentVisible = null;

    #[ORM\Column]
    private ?bool $featuredImageVisible = null;

    #[ORM\Column(length: 255, unique: true)]
    #[Gedmo\Slug(fields: ['title'])]
    private ?string $slug = null;

    #[ORM\ManyToOne(inversedBy: 'blogPosts')]
    private ?ImageGallery $gallery = null;

    /**
     * @var Collection<int, ListEntry>
     */
    #[ORM\ManyToMany(targetEntity: ListEntry::class, inversedBy: 'blogPosts', cascade: ["persist"])]
    private Collection $list;

    #[ORM\Column(nullable: true)]
    private ?int $duration = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $scheduleDate = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $scheduleOffset = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $endDate = null;

    public function __construct()
    {
        $this->list = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getTemplate(): ?BlogPostTemplate
    {
        return $this->template;
    }

    public function setTemplate(?BlogPostTemplate $template): static
    {
        $this->template = $template;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): static
    {
        $this->active = $active;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featuredImage;
    }

    public function getFeaturedImageUrl(): ?string
    {
        if (!$this->featuredImage) {
            return null;
        }
        if (strpos($this->featuredImage, '/') !== false) {
            return $this->featuredImage;
        }
        return sprintf('/posts/uploads/%s', $this->featuredImage);
    }

    public function setFeaturedImage(?string $featuredImage): static
    {
        $this->featuredImage = $featuredImage;

        return $this;
    }

    public function isTitleVisible(): ?bool
    {
        return $this->titleVisible;
    }

    public function setTitleVisible(bool $titleVisible): static
    {
        $this->titleVisible = $titleVisible;

        return $this;
    }

    public function isContentVisible(): ?bool
    {
        return $this->contentVisible;
    }

    public function setContentVisible(bool $contentVisible): static
    {
        $this->contentVisible = $contentVisible;

        return $this;
    }

    public function isFeaturedImageVisible(): ?bool
    {
        return $this->featuredImageVisible;
    }

    public function setFeaturedImageVisible(bool $featuredImageVisible): static
    {
        $this->featuredImageVisible = $featuredImageVisible;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getGallery(): ?ImageGallery
    {
        return $this->gallery;
    }

    public function setGallery(?ImageGallery $gallery): static
    {
        $this->gallery = $gallery;

        return $this;
    }

    /**
     * @return Collection<int, ListEntry>
     */
    public function getList(): Collection
    {
        return $this->list;
    }

    public function addList(ListEntry $list): static
    {
        if (!$this->list->contains($list)) {
            $this->list->add($list);
        }

        return $this;
    }

    public function removeList(ListEntry $list): static
    {
        $this->list->removeElement($list);

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getScheduleDate(): ?\DateTimeInterface
    {
        return $this->scheduleDate;
    }

    public function setScheduleDate(?\DateTimeInterface $scheduleDate): static
    {
        $this->scheduleDate = $scheduleDate;

        return $this;
    }

    public function getScheduleOffset(): ?string
    {
        return $this->scheduleOffset;
    }

    public function setScheduleOffset(?string $scheduleOffset): static
    {
        $this->scheduleOffset = $scheduleOffset;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(?\DateTimeInterface $startDate): static
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(?\DateTimeInterface $endDate): static
    {
        $this->endDate = $endDate;

        return $this;
    }
}

src/Entity/Image.php
<?php

namespace App\Entity;

use App\Repository\ImageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: ImageRepository::class)]
class Image
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $file = null;

    #[ORM\Column(nullable: true)]
    private ?bool $disabled = null;

    #[ORM\Column(length: 255, unique: true)]
    #[Gedmo\Slug(fields: ['file'])]
    private ?string $slug = null;

    /**
     * @var Collection<int, ImageGallery>
     */
    #[ORM\ManyToMany(targetEntity: ImageGallery::class, inversedBy: 'images')]
    private Collection $gallery;

    #[ORM\Column(nullable: true)]
    private ?bool $showCaption = null;

    public function __construct()
    {
        $this->gallery = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->title ?? $this->slug;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function getFileUrl(): ?string
    {
        if (!$this->file) {
            return null;
        }
        if (strpos($this->file, '/') !== false) {
            return $this->file;
        }
        return sprintf('/images/uploads/%s', $this->file);
    }

    public function setFile(?string $file): static
    {
        $this->file = $file;

        return $this;
    }

    public function isDisabled(): ?bool
    {
        return $this->disabled;
    }

    public function setDisabled(?bool $disabled): static
    {
        $this->disabled = $disabled;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * @return Collection<int, ImageGallery>
     */
    public function getGallery(): Collection
    {
        return $this->gallery;
    }

    public function addGallery(ImageGallery $gallery): static
    {
        if (!$this->gallery->contains($gallery)) {
            $this->gallery->add($gallery);
        }

        return $this;
    }

    public function removeGallery(ImageGallery $gallery): static
    {
        $this->gallery->removeElement($gallery);

        return $this;
    }

    public function isShowCaption(): ?bool
    {
        return $this->showCaption;
    }

    public function setShowCaption(?bool $showCaption): static
    {
        $this->showCaption = $showCaption;

        return $this;
    }
}

templates/blog/article.html.twig
<div class="list-group list-group-flush w-100">
    <div class="list-group-item fs-4 text-uppercase text-bg-dark blur-dark">{{ article.title }}</div>
</div>

    {% if article.featuredImageVisible and not article.contentVisible %}
    <div class="p-3 my-auto">
        <div class="row g-3">
            <div class="col-12">
                <img src="{{ asset(article.featuredImageUrl)|imagine_filter('sample_image') }}" class="img-fluid img-thumbnail" alt="{{ article.title }}" style="max-height: 800px">
            </div>
        </div>
    </div>
    {% endif %}

    {% if article.featuredImageVisible and article.contentVisible %}
<div class="p-3 my-auto">
        <div class="row g-3">
            <div class="col-4">
                <img src="{{ asset(article.featuredImageUrl)|imagine_filter('sample_image') }}" class="img-fluid img-thumbnail" alt="{{ article.title }}" style="max-height: 600px">
            </div>
            <div class="col-7">
                {#
                {% if article.titleVisible %}
                <div class="col">
                    <div class="fw-bold display-4">{{ article.title }}</div>
                </div>
            {% endif %}
                #}



                <div class="col fs-4" style="text-align: justify!important;">
                    {{ article.content|raw }}
                </div>

            </div>
        </div>
</div>
    {% else %}

        {% if article.contentVisible %}
            <div class="mx-auto my-auto p-3 pt-0">
                <div class="fs-4">
                    {{ article.content|raw }}
                </div>
            </div>
        {% endif %}
    {% endif %}

templates/blog/carousel.html.twig
<div class="list-group list-group-flush w-100">
    <div class="list-group-item fs-4 text-uppercase text-bg-dark blur-dark">{{ article.title }}</div>
</div>

    <div class="main-carousel w-100" {{ stimulus_controller('gallery') }}>
        {% for image in article.gallery.images %}
            <img src="{{ asset(image.fileUrl)|imagine_filter('gallery') }}" class="d-block" style="height: 740px; max-height: 740px"  alt="{{ image }}">
        {% endfor %}
    </div>

templates/blog/list.html.twig
<div class="list-group list-group-flush w-100">
    <div class="list-group-item fs-4 text-uppercase text-bg-dark blur-dark">{{ article.title }}</div>
</div>

<ul class="list-group list-group-flush w-100 mb-auto border-0">
    {% for listEntry in article.list %}
        {% if listEntry.title %}
            {% if loop.index0 != 0 %}{% set margin = "mt-3" %}{% endif %}
            <li class="list-group-item d-flex justify-content-start align-items-center text-bg-tertiary border-0 {{ margin ?? '' }}  text-white fw-bold  fs-5">
                {{ listEntry.description }}
            </li>
        {% else %}
            <li class="list-group-item d-flex justify-content-start align-items-center border-0 border-top text-bg-tertiary text-white fs-6" style="border-color: #255372!important">
                <div style="width: 250px" class="me-3">{{ listEntry.description }}</div>
                <div>{{ listEntry.content }}</div>
            </li>
        {% endif %}

    {% endfor %}
</ul>

{% if article.contentVisible %}
    <div class="align-self-center fs-4 mb-5">
        {{ article.content|raw }}
    </div>
{% endif %}

templates/blog/schedule.html.twig
<div class="list-group list-group-flush w-100">
    <div class="list-group-item fs-4 text-uppercase text-bg-dark blur-dark">
        {% if article.scheduleDate %}
            Änderungen für den {{ article.scheduleDate|date('d.m.Y') }}
        {% else %}
            Änderungen für morgen
        {% endif %}
    </div>
</div>

<ul class="list-group list-group-flush w-100 mb-auto">
    <div class="list-group-item small text-bg-tertiary">
        <div class="row g-3">
            <div class="col-6">
                <div class="row g-1">
                    <div class="col-2 text-uppercase">Stunde</div>
                    <div class="col-3 text-uppercase">Klasse</div>
                    <div class="col-3 text-uppercase">Fach</div>
                    <div class="col-4 text-uppercase">Raum</div>
                </div>
            </div>
            <div class="col-6">
                <div class="row h-100">
                    <div class="col-3 align-self-center text-uppercase">
                        Typ
                    </div>
                    <div class="col-9 align-self-center text-uppercase">
                        Änderungen
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% for entry in courseEntries %}
        <div class="list-group-item small text-bg-primary" style="background-color: {{ entry.scheduleType.color ~ "20!important" }}">
            <div class="row g-3">
                <div class="col-6">
                    <div class="row g-1">
                        <div class="col-2 text-uppercase fw-bold fs-6">{{ entry.entryTime.name|trans }}</div>
                        <div class="col-3 text-uppercase fw-bold fs-6">{{ entry.course }}</div>
                        <div class="col-3 text-uppercase fw-bold fs-6">{{ entry.plannedSubject }}</div>
                        <div class="col-4 text-uppercase fw-bold fs-6"><span class="fa fa-fw fa-location-dot"></span>{{ entry.plannedRoom }}</div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="row h-100">
                        <div class="col-3 align-self-center text-uppercase" style="color: {{ entry.scheduleType.color ~ "!important" }}">
                            {{ entry.scheduleType }}
                        </div>
                        <div class="col-9 align-self-center text-uppercase">
                            <span class="fa fa-fw fa-person-chalkboard me-2"></span>{{ entry.plannedTeacher }}{% if entry.updatedTeacher %}<span class="fa mx-1 fa-fw fa-angle-double-right"></span><span class="fw-bold" style="color: {{ entry.scheduleType.color ~ "!important" }}">{{ entry.updatedTeacher }}</span>{% endif %}
                            {% if entry.updatedRoom != null and entry.updatedRoom != entry.plannedRoom %}
                                <span class="fa fa-fw fa-location-dot ms-2 me-1"></span>{{ entry.plannedRoom }}<span class="fa mx-1 fa-fw fa-angle-double-right"></span><span class="fw-bold" style="color: {{ entry.scheduleType.color ~ "!important" }}">{{ entry.updatedRoom }}</span>
                            {% endif %}
                            {% if entry.updatedSubject != null and entry.plannedSubject != entry.updatedSubject %}
                                <span class="fa fa-fw fa-book ms-2 me-1"></span>{{ entry.plannedSubject }}<span class="fa mx-1 fa-fw fa-angle-double-right"></span><span class="fw-bold" style="color: {{ entry.scheduleType.color ~ "!important" }}">{{ entry.updatedSubject }}</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="list-group-item small text-bg-primary">
            Keine Einträge für morgen vorhanden.
        </div>
    {% endfor %}
</ul>

{% if article.contentVisible %}
    <div class="align-self-center fs-5 mb-5">
        {{ article.content|raw }}
    </div>
{% endif %}